stages:
  - build

image: eu.gcr.io/qa-cloud-186211/gcr_io_k8s-skaffold_sisyphus-build-env:90d2039

sample prepare:
  stage: prepare
  script:
    - go build -x
  tags:
    - sisyphus-self-builder
#  cache:
#    paths:
#      - .go/
#    policy: pull-push
#    key: sisyphus-cache
