stages:
  - build

image: eu.gcr.io/qa-cloud-186211/gcr.io/k8s-skaffold/sisyphus-build-env:8ddcc2b

basic build:
  stage: build
  script:
    - go build -x
  tags:
    - sisyphus-self-builder
  artifacts:
    expire_in: 1 day
    paths:
      - ./sisyphus