stages:
  - build

image: eu.gcr.io/qa-cloud-186211/gcr.io/k8s-skaffold/sisyphus-build-env:dbff40d

basic build:
  stage: build
  script:
    # Test for % char
    - echo "Hello $(date +%Y-%m-%d)"
    - go build -v -buildmode=exe
  tags:
    - sisyphus-self-builder
  artifacts:
    expire_in: 1 day
    paths:
      - ./sisyphus