##
## Register a runner
##
POST https://git.example.com/api/v4/runners
Content-Type: application/json

{
  "token": "GitLabToken",
  "tag_list": [
    "sisyphus-debug"
  ],
  "description": "Test Runner"
}

###