apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
    - image: gcr.io/k8s-skaffold/sisyphus-runner
      context: ./dockerfiles/builder
      docker:
        dockerfile: Dockerfile