apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
    - image: gcr.io/k8s-skaffold/sisyphus-build-env
      docker:
        dockerfile: Dockerfile
        target: build-env

    - image: gcr.io/k8s-skaffold/sisyphus-runner
      docker:
        dockerfile: Dockerfile
        target: runner
