apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
    - image: gcr.io/k8s-skaffold/sisyphus-build-env
      docker:
        dockerfile: Dockerfile
        target: build-env

    - image: gcr.io/k8s-skaffold/sisyphus-runner
      docker:
        dockerfile: Dockerfile
        target: runner
deploy:
  helm:
    releases:
      - name: sisyphus-dev-runner
        chartPath: files/charts/sisyphus
        values:
          image: gcr.io/k8s-skaffold/sisyphus-runner

        recreatePods: true

profiles:
  - name: production
    deploy:
      helm:
        releases:
          - name: sisyphus-runner
            chartPath: files/charts/sisyphus
            values:
              image: gcr.io/k8s-skaffold/sisyphus-runner
            recreatePods: true
            overrides:
              runnerConf:
                runnerName: sisyphus-production
                runnerToken: tZbC3Lq5kLfzdGXhLUBj

  - name: self-builder
    deploy:
      helm:
        releases:
          - name: sisyphus-self-builder
            chartPath: files/charts/sisyphus
            values:
              image: gcr.io/k8s-skaffold/sisyphus-runner
            recreatePods: true
            overrides:
              runnerConf:
                runnerName: sisyphus-self-builder
                runnerToken: sqYUuQ9wC-zxNBFUx36w
                namespace: sisyphus-test

  - name: sisyphus-staging
    deploy:
      helm:
        releases:
          - name: sisyphus-staging
            chartPath: files/charts/sisyphus
            values:
              image: gcr.io/k8s-skaffold/sisyphus-runner
            recreatePods: true
            overrides:
              runnerConf:
                gitlabUrl: https://git.dev-staging.promon.no
                runnerName: sisyphus-staging-builder
                runnerToken: t1sfza1MGzeisdcfyWVs
                namespace: sisyphus-test