apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sisyphus.fullname" . }}
  labels:
{{ include "sisyphus.labels" . | indent 4 }}
data:
  conf.yaml: |
    runner_name: {{ .Values.runnerConf.runnerName }}
    gitlab_url: https://git.dev.promon.no
    runner_token: {{ .Values.runnerConf.runnerToken | quote }}
    k8s_namespace: {{ .Values.runnerConf.namespace | quote }}
    gcp_cache_bucket: gitlab_ci_cache
    default_node_selector:
      class: sisyphus
      cloud.google.com/gke-preemptible: "true"
    default_resource_request:
      - type: cpu
        quantity: 3600m
      - type: storage
        quantity: 10Gi
      - type: ephemeral-storage
        quantity: 100Mi