apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sisyphus.fullname" . }}
  labels:
{{ include "sisyphus.labels" . | indent 4 }}
data:
  conf.yaml: |
    gitlab_url: https://git.dev.promon.no
    runner_token: {{ .Values.runnerConf.runnerToken | quote }}
    k8s_namespace: sisyphus
    gcp_cache_bucket: gitlab_ci_cache
    default_resource_request:
      - type: cpu
        quantity: 3600m
      - type: storage
        quantity: 10Gi
      - type: ephemeral-storage
        quantity: 100Mi