# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

#GET https://git.dev.promon.no/api/v4/projects?per_page=500
#Accept: application/json
#Private-Token: AaNZWjA47W9FTin2gGGh


GET https://git.dev.promon.no/api/v4/projects/1/pipelines/9265
Accept: application/json
Private-Token: AaNZWjA47W9FTin2gGGh
###


POST https://git.dev.promon.no/api/v4/projects/1/pipelines/9265/retry
Accept: application/json
Private-Token: AaNZWjA47W9FTin2gGGh

###