# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

##
## Register a runner
##
POST https://git.dev.promon.no/api/v4/runners
Content-Type: application/json

{
  "token": "xwBZ3KgHmKR8yYD3QA9U",
  "tag_list": [
    "potato",
    "sisyphus"
  ],
  "description": "New runner"
}

###
# RESPONSE:
#{
#  "id": 129,
#  "token": "kxZppSfxQjM6aAmAoxjo"
#}

POST https://git.dev.promon.no/api/v4/jobs/request
Content-Type: application/json

{
  "token": "xYTmzTuMux7gfszyjfyh",
  "info": {
    "features": {
      "variables": true,
      "image": true,
      "services": true,
      "artifacts": true,
      "cache": true,
      "shared": true,
      "upload_multiple_artifacts": true,
      "refspecs": true
    }
  }
}

###

POST /api/v4/jobs/request HTTP/1.1
Host: git.dev.promon.no
User-Agent: Go-http-client/1.1
Content-Length: 32
Accept: application/json
Accept-Encoding: gzip

{"token":"kxZppSfxQjM6aAmAoxjo"}


# 157094
PATCH https://git.dev.promon.no/api/v4/jobs/157094/trace
Content-Type: text/plain
Content-Range: 13-25
Job-Token: MEypaqwVxju9maGxnA3u

What is LOG !

###

PUT https://git.dev.promon.no/api/v4/jobs/157094
Content-Type: application/json

{
  "token": "MEypaqwVxju9maGxnA3u",
  "state": "failed"
}

###